### ISSUE TITLE
Error with Pandas version 2

### ISSUE THREAD

**Issue by davideyre** [vvcb/comorbidipy#3]
* comorbidipy version: 0.5.0
* Python version: 3.9.6
* Operating System: macOS

### Description

Comorbidipy works fine with pandas 1.4.0, but when trying to run with a more recent version I get this error, e.g. version 1.5.0 or version 2.0.1

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from comorbidipy import comorbidity
  File "venv/lib/python3.9/site-packages/comorbidipy/__init__.py", line 7, in <module>
    from .calculator import comorbidity, hfrs, disability
  File "venv/lib/python3.9/site-packages/comorbidipy/calculator.py", line 5, in <module>
    from pandas.core.common import SettingWithCopyWarning
ImportError: cannot import name 'SettingWithCopyWarning' from 'pandas.core.common' (venv/lib/python3.9/site-packages/pandas/core/common.py)
```

The issue seems to be that the import is now in pandas.errors, this doesn't work - 

```
from pandas.core.common import SettingWithCopyWarning
```

But this does

```
 from pandas.errors import SettingWithCopyWarning
```

**Comment by Padmapalita** [comment]
Upvoting this issue.

**Comment by rbngz** [comment]
It seems to be fixed with the recent commit but has not yet been published to PyPi.
Simply install from Github using the commit hash:

```
pip install git+https://github.com/vvcb/comorbidipy.git@c676a8067ce343704d75bcf8180f9baa1ac47664
```

Make sure to uninstall any previous version first using

```
pip uninstall comorbidipy
```

**Comment by smgpulse007** [comment]
Goto calculator.py
~AppData\Local\Programs\Python\Python311\Lib\site-packages\comorbidipy

Change `from pandas.core.common import SettingWithCopyWarning`

TO
`from pandas.errors import SettingWithCopyWarning`

@vvcb This fixes the issue and the import works as described in the docs

**Comment by MattStammers** [comment]
> It seems to be fixed with the recent commit but has not yet been published to PyPi. Simply install from Github using the commit hash:
> 
> ```
> pip install git+https://github.com/vvcb/comorbidipy.git@c676a8067ce343704d75bcf8180f9baa1ac47664
> ```
> 
> Make sure to uninstall any previous version first using
> 
> ```
> pip uninstall comorbidipy
> ```

@rbngz is right. @vvcb you need to patch the current pypi version.

**Comment by vvcb** [comment]
Closing this issue as pandas has been replaced with polars in v0.7.0 for performance reasons.
